<a href="https://colab.research.google.com/github/yeanni-w0n/esaa_assignment_yw01/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%99%84%EB%B2%BD%EA%B0%80%EC%9D%B4%EB%93%9C_p_87~117.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Chap2. 사이킷런으로 시작하는 머신러닝**

사이킷런(scikit-learn)은 가장 쉽고 파이썬다운 API를 제공함. 머신러닝을 위한 알고리즘과 편리한 프레임워크 형태로 되어있고 오랜 기간동안 검증된 성숙한 라이브러리로 각인되어 있음.


---

지도학습을 통해 명확한 정답이 주어진 데이터를 먼저 학습한 뒤 미지의 정답을 예측할 수 있음.


In [1]:
%pip install scikit-learn

In [2]:
import sklearn
print(sklearn.__version__)

1.2.2


In [3]:
from sklearn.datasets import load_iris
# 사이킷런에서 자체적으로 제공하는 데이터 세트를 생성하는 모듈의 모임
# 붓꽃 데이터 세트 생성
from sklearn.tree import DecisionTreeClassifier
# 트리 기반 ML 알고리즘을 구현한 클래스의 모임
# 의사 결정 트리
from sklearn.model_selection import train_test_split
# 학습/검증/예측 데이터로 분리하거나 최고의 하이퍼 파라미터로 평가
# 하이퍼 파라미터를 통해 머신러닝 알고리즘의 성능을 튜닝 가능
# 학습 데이터와 테스트 데이터로 데이터 세트를 분류

In [4]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

In [5]:
import pandas as pd

# 붓꽃 데이터 세트 로딩
iris = load_iris()

# iris.data는 iris 데이터 셋에서 피처만으로 된 데이터를 np로 가지고 있음.
iris_data = iris.data

# iris.target은 붓꽃 데이터 셋에서 레이블(결정값) 데이터를 np로 가지고 있음
iris_label = iris.target
print('iris target 값 :', iris_label)
print('iris target 명 :', iris.target_names)

# 붓꽃 데이터 셋을 자세히 보기 위해 DF로 변경
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

iris target 값 : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명 : ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [6]:
X_train, X_test, y_train, y_test = train_test_split(iris_data,
                                                    iris_label,
                                                    test_size=0.2,
                                                    random_state=11)
# 학습용 데이터로 학습된 모델이 얼마나 뛰어난 성능을 가지는지 평가
# test_size = 0.2 : 테스트 데이터가 전체의 20%
# random_state : seed 난수 발생 값
# 수행할 떄마다 동일한 데이터 세트로 분리하기 위해 random_state

In [14]:
#DecisionTreeClassifier 객체 생성
#의사 결정 나무 (머신러닝 분류 알고리즘)
dt_clf = DecisionTreeClassifier(random_state=11)
#학습 수행
dt_clf.fit(X_train, y_train)
#fit 메서드 안에 학습용 피쳐 데이터 속성과 결정값 데이터 세트

DecisionTreeClassifier(random_state=11)

In [8]:
dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [12]:
#학습이 완료된 DecisionTreeClassfier 객체에서 테스트 데이터 셋으로 예측
#예측은 반드시 학습 데이터가 아닌 다른 데이터를 이용해야 함
pred = dt_clf.predict(X_test)
#테스트용 피처 데이터 세트를 입력해 호출

# 예측 결과를 기반으로 예측 성능 평가
# 정확도 측정 : 에측 결과가 실제 레이블 값과 얼마나 정확히 맞는지
# accuracy_score() : 사이킷런의 정확도 측정
from sklearn.metrics import accuracy_score
print('예측 정확도 : {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도 : 0.9333


In [11]:
pred = dt_clf.predict(X_test)
from sklearn.metrics import accuracy_score
print('예측 정확도 : {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도 : 0.9333


**분류 프로세스 정리**

1. 데이터 세트 분리 : 데이터를 학습 데이터와 테스트 데이터로 분리함
2. 모델 학습 : 학습 데이터로 ML 알고리즘을 적용해 모델을 학습시킴
3. 예측 수행 : 학습된 ML 모델을 이용해 테스트 데이터의 분류를 예측
4. 평가 : 이렇게 예측된 결과값과 테스트 데이터의 실제 결과값을 비교함으로써 ML 모델 성능을 평가함

**Estimator_fit(), predict()**



*   fit(): ML 모델을 학습
*   predict(): 학습된 모델을 예측



**Estimator class**



*   분류(classifier)




1.   DecisionTreeClassifier
2.   RandomForestClassifier
3. GradientBoostingClassifier
4. SVC
5.GaussianNB





*   회귀(Regressor)



1.   LinearRegression
2. Ridge
3. Lasso
4. RandomForestRegressor
5. GradientBoostingRegressor




In [15]:
# 내장된 예제 데이터 세트
# fetch 계열 명령 : 데이터 크기가 커서 패키지에 처음부터 저장돼 있지 않고 인터넷에서 내려받아 홈 디렉터리 아래의 서브 디렉터리에 저장한 후 추후 불러들이는 데이터
# datasets.make_classifications() : 분류를 위한 데이터 세트를 만듦
# datasets.make_blobs (클러스터링을 위한 데이터셋을 무작위 생성)
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))
# Bunch : 파이썬의 딕셔너리와 유사

<class 'sklearn.utils._bunch.Bunch'>


In [16]:
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들 :',keys)
# 데이터 키 : 피쳐들의 데이터 값
# 데이터 세트가 딕셔너리 형태이므로 피쳐 데이터 값을 추출 :
# 데이터 세트를 이용

붓꽃 데이터 세트의 키들 : dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [17]:
print('\n feature_name의 type:', type(iris_data.feature_names))
print('feature_names 의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:', type(iris_data.target_names))
print('target names의 shape:', len(iris_data.target_names))


 feature_name의 type: <class 'list'>
feature_names 의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
target names의 shape: 3


In [18]:
print(iris_data.target_names)
print('\n data의 type:', type(iris_data.data))
print(' data의 shape:', iris_data.data.shape)
print(iris_data['data'])

print('\n target의 type:', type(iris_data.target))
print('\n target의 shape:', len(iris_data.target.shape))
print(iris_data.target)

['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
 data의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 

In [19]:
# 학습 / 검증 데이터 세트 분리 : train_test_split()
# 학습용 데이터 셋 = 테스트용 데이터 셋
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris() # 데이터 셋 불러오기
df_clf = DecisionTreeClassifier() # 의사결정나무 생성
train_data = iris.data # 모든 데이터로 학습
train_label = iris.target # y값
dt_clf.fit(train_data, train_label) # 모든 데이터로 학습

# 학습 데이터 세트로 예측 수행
pred = dt_clf.predict(train_data) # 그 데이터로 예측
print('예측 정확도:', accuracy_score(train_label, pred))
# 예측 정확도 100%, something wrong

예측 정확도: 1.0


In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [21]:
dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data,
                                                    iris_data.target,
                                                    test_size = 0.3,
                                                    random_state=121)

In [22]:
df_clf.fit(X_train, y_train)
pred = df_clf.predict(X_test)
print('예측 정확도:{0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도:0.9556


**교차 검증**

---
의사결정나무는 과적합에 취약함. 모델이 학습 데이터에만 과도하게 최적화되어 실제 에측을 다른
데이터로 수행하면 예측 성능이 과도하게 떨어짐. 고정된 학습 테스트 데이터로만 평가하게 되면 결국 테스트 데이터에만 과적합되는 학습 모델이 만들어져 다른 테스트용 데이터가 들어올 경우 성능이 저하되는데 이걸 개선한 것이 교차 검증


In [23]:
# k 폴드 교차 검증
# k개의 데이터 폴드 세트를 만들어서 k번만큼 각 폴드 세트에 학습과 검증 평가를 반복적으로 수행
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state = 156)

# 5개의 폴드 세트로 분리하는 kfold 객체와 폴드 세트별 정확도를 담을 리스트
kfold = KFold(n_splits=5)
cv_accuracy=[]
print('붓꽃 데이터 세트 크기:', features.shape[0])
# 150개의 데이터, 5개의 스플릿이므로 4/5개인 120개가 학습용 데이타

붓꽃 데이터 세트 크기: 150


In [24]:
n_iter = 0
# kfold 객체의 split()을 호출하면 폴드별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features) :
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    # 학습 및 예측
    df_clf.fit(X_train, y_train)
    pred = df_clf.predict(X_test)
    n_iter += 1
    # 반복할 떄마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기:{2},검증 데이터 크기: {3}'.format(
        n_iter, accuracy, train_size, test_size
    ))


#1 교차 검증 정확도 :1.0, 학습 데이터 크기:120,검증 데이터 크기: 30

#2 교차 검증 정확도 :1.0, 학습 데이터 크기:120,검증 데이터 크기: 30

#3 교차 검증 정확도 :0.9, 학습 데이터 크기:120,검증 데이터 크기: 30

#4 교차 검증 정확도 :0.9333, 학습 데이터 크기:120,검증 데이터 크기: 30

#5 교차 검증 정확도 :0.8333, 학습 데이터 크기:120,검증 데이터 크기: 30


**Stratified K fold**-

---


불균형한 분포도를 가진 레이블 데이터 집합을 위한 kfold


---


- 특정 레이블 값이 특이하게 많거나 적어서 값의 분포가 한 쪽으로 치우치는 것
- kfold 교차 검증을 사용하는 경우 랜덤하게 고른다고 하더라도 제대로 비율 반영을 하지 못할 수 있음
- Stratified k fold는 데이터 집합이 원본 데이터 집합의 분포를 학습 검증 세트에 제대로 분배하지 못하는 경우 해결
-kfold 교차검증에서 학습 레이블과 검증 레이블이 다른 값으로 추출된다면 포함되지 않은 데이터는 아예 학습하지 못하므로 그 값은 예측 불가능함.
-StratifiedKfold는 Kfold의 전체 레이블 분포도 미반영 문제를 해결할 수 있음.

In [25]:
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [26]:
kfold = KFold(n_splits=3)
n_iter = 0
for train_index, test_index in kfold.split(iris_df) :
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차 검증:{0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증:1
학습 레이블 데이터 분포:
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64
## 교차 검증:2
학습 레이블 데이터 분포:
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64
## 교차 검증:3
학습 레이블 데이터 분포:
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64


In [28]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits = 3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']) :
    # kfold와 달리 split 안에 피처 / 레이블 데이터 모두 필요
    n_iter =1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('교차 검증 : {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

# 학습 레이블과 검증 레이블 모두 데이터의 분포도가 동일하게 할당됨.

교차 검증 : 1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
교차 검증 : 1
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
교차 검증 : 1
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


In [29]:
# p110
# StratifiedKFold를 이용해 데이터 분리
dt_clf = DecisionTreeClassifier(random_state=156)
skfold = StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

# StratifiedKFold의 split() 호출시 반드시 레이블 데이터셋도 입력
for train_index, test_index in skfold.split(features, label) :
    # split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)

    # 반복 시마다 정확도 측정
    n_iter += 1
    acuuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    print('\n#{0} 교차 검증 정확도 : {1}, 학습 데이터 크기:{2}, 검증 데이터 크기 :{3}'.
          format(n_iter, accuracy, train_size, test_size))
    print("#{0} 검증 세트 인덱스:{1}".format(n_iter, test_index))
    cv_accuracy.append(accuracy)

# 교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차검증별 정확도 : ', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도 : 0.8333, 학습 데이터 크기:100, 검증 데이터 크기 :30
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 : 0.8333, 학습 데이터 크기:100, 검증 데이터 크기 :30
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 : 0.8333, 학습 데이터 크기:100, 검증 데이터 크기 :30
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차검증별 정확도 :  [0.8333 0.8333 0.8333]
## 평균 검증 정확도: 0.8333


### **간편 교차검정 - cross_val_score()**

---


kfold 데이터 학습 과정을 한꺼번에 수행

---


**kfold 데이터 학습 과정**
1. 폴드 세트 설정
2. for loop에서 학습/검증 인덱스 추출을 반복
3. 반복 학습/예측 후 성능 반환


In [30]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state = 156)

data = iris_data.data
label = iris_data.target

# 성능 지표는 정확도(accuracy), 교차 검증 세트는 3개
scores = cross_val_score(dt_clf, data, label,
                         scoring = 'accuracy', cv=3)
# cv로 지정된 횟수만큼 scoring에 지정된 평가 지표로 평가 결괏값을 반환
print('교차검증별 정확도:',np.round(scores, 4))
print('평균검증 정확도:', np.round(np.mean(scores), 4))


교차검증별 정확도: [0.98 0.94 0.98]
평균검증 정확도: 0.9667


### **GridSearchCV**


---


- 하이퍼파라미터 : 머신러닝 알고리즘을 구성하는 주요 구성 요소
- 하이퍼파라미터의 값을 조정하여 알고리즘의 예측 성능 향상
-  GridSearchCV를 이용해 분류/회귀에 이용되는 하이퍼파라미터를 입력하여 최적의 파라미터 도출 방안을 제공

In [31]:
grid_parameters = {
    'max_depth' : [1,2,3],
    'min_samples_split' : [2,3]
}
# 총 6회에 걸쳐 파라미터를 바꿔 실행하여 최적의 결과 도출

In [32]:
# 결정 트리 알고리즘에 최적화 파라미터를 순차 적용해 최적의 하이퍼 파라미터 추출

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# 데이터 로딩후 학습/테스트 데이터 분리
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(
    iris_data.data, iris_data.target, test_size = 0.2,
    random_state=121
)
dtree = DecisionTreeClassifier()

# 파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth' : [1,2,3],
              'min_samples_split':[2,3]}

In [33]:
import pandas as pd

#param_grid의 하이퍼 파라미터를 3개의 train, test set fold 나누어 테스트 수행 설정
### refit=True가 default임. True이면 가장 좋은 파라미터 설정으로 재학습시킴
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

#붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

#GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score', 'split0_test_score', 'split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [34]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도 :{0:4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도 :0.975000


In [38]:
# GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_
# GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도: 0.966667
